function Project = importOASPL(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PROJECT = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  PROJECT = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  PROJECT = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Project = importfile("C:\Users\to232\Documents\Winter 2024\Ph 530 - Computational Physics\p530final\530 Project.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Apr-2024 14:21:05

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 11];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "PeakOASPLFlat"];
opts.SelectedVariableNames = "PeakOASPLFlat";
opts.VariableTypes = ["char", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
Project = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Project = [Project; tb]; %#ok<AGROW>
end
Project = table2array(Project);
end